# -*- coding: utf-8 -*-
"""Tugas 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S07DUdBU9vIRBwO2_gNahLC6w85R3uVc
"""

data_kotor = "   #001-wahyu aji-informatika-python,java,php-aktif   "

data_bersih = data_kotor.strip().replace('#', '')

list_data = data_bersih.split("-")

id_pendaftaran = list_data[0]
nama_lengkap = list_data[1].title()
program_studi = list_data[2].title()
skill_dikuasai = list_data[3]
status = list_data[4].upper()

list_skill = skill_dikuasai.split(",")
skill_join = " & ".join(list_skill)

panjang_id = len(id_pendaftaran)
jumlah_skill = len(list_skill)

print("=====================================")
print("Hasil Validasi Data".center(35))
print("=====================================")
print(f"ID Pendaftaran: {id_pendaftaran}")
print(f"Nama Lengkap: {nama_lengkap}")
print(f"Program Studi: {program_studi}")
print(f"Skill Dikuasai: {skill_join}")
print(f"Jumlah Skill: {jumlah_skill}")
print(f"Status: {status}")
print("=====================================")

"""1. Pembersihan Data (strip & replace): Fungsi .strip() digunakan untuk membuang spasi kosong di paling depan dan belakang teks. Fungsi .replace('#', '') digunakan untuk menghilangkan tanda pagar.

2. Memecah String (split): Teks yang sudah bersih dipecah menjadi list dengan fungsi .split('-') agar kita bisa mengambil ID, Nama, Prodi, dsb. secara terpisah

3. Fungsi len() digunakan untuk menghitung jumlah skill yang dikuasai. Variabel tersebut mengambil dari len(list_skill) atau list_skill yang ada di bagian ke tiga. Code ini digunakan untuk menghitung berapa variabel yang dimasukkan tersebut. Code panjang_ id digunakan untuk menghitung panjangnya angka dalam ID. Hal ini digunakan apabila code tersebut diminta untuk menghitung banyaknya angka tersebut.

4. Variabel skill_mentah berisi "python,java,php" yang masih menyatu, sehingga dipecah menggunakan split(",") menjadi list ['python', 'java', 'php']. Karena format list kurang enak dibaca, elemen-elemennya digabung kembali menggunakan " & ".join(daftar_skill) sehingga menghasilkan string "python & java & php" yang lebih rapi untuk ditampilkan.

5. f"..." → untuk memasukkan variabel langsung (F-String)
\t → biar rapi (tab)
\n → pindah baris (kalau pakai satu print)
join() → gabung list jadi string
len() → hitung jumlah skill
"""